### ISSUE TITLE
PlayerCharacter Art

### ISSUE THREAD

**Issue by KierenP** [KierenP/Heist#11]
The player sprite. A **top down projection of soldier**, holding a gun. 

It needs to be in a sprite sheet that includes the animation for _shooting_ (fire leaving barrel) and also animated _walking_.

**Comment by Stavy53** [comment]
It shall be done oh overlord KierenP

**Comment by KierenP** [comment]
Good, comrade @Stavy53

**Comment by KierenP** [comment]
Start with just the player sprite, and then animate it later @Stavy53
